@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQVVUSCIsImp0aSI6ImM4MzMwMjBhLWRjMmEtNDcxZS1iZGQyLTM0ZGRjYTQ1ZjhiZSIsImlhdCI6MTc4OTgyMDI0NiwiZXhwIjoxNzg5ODIxMTQ2LCJzdWIiOiIxNWMzMTU4MS0yOTk5LTQ0NDYtYTY1Ni03MjgzNTBiZDgwZWMifQ.JFEI6k-ymk_Lh4TblUEpjXopcHEv23t0tk8ndN-_Nh4

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Sergio Marking",
  "email": "sargio.markina@gmail.com",
  "phone": "9690578859"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Manish",
  "email": "manish.gupta@example.com",
  "phone": "8246391570"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Kavya",
  "email": "kavya.reddy@example.com",
  "phone": "9174526380"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Harsh",
  "email": "harsh.bansal@example.com",
  "phone": "7569284130"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Pooja",
  "email": "pooja.joshi@example.com",
  "phone": "8693157240"
}