POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Microserver",
  "email": "micro.markina@gmail.com",
  "phone": "8847859657"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Manish",
  "email": "manish.gupta@example.com",
  "phone": "8246391570"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Kavya",
  "email": "kavya.reddy@example.com",
  "phone": "9174526380"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Harsh",
  "email": "harsh.bansal@example.com",
  "phone": "7569284130"
}

###

POST {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Pooja",
  "email": "pooja.joshi@example.com",
  "phone": "8693157240"
}