@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQVVUSCIsImp0aSI6IjM3MjQ3ZjZlLWEyMzItNDNlYi05YzAyLTA3ZjY0ZTBhNTA4NSIsImlhdCI6MTc4OTgwNzU1OSwiZXhwIjoxNzg5ODA4NDU5LCJzdWIiOiIxNWMzMTU4MS0yOTk5LTQ0NDYtYTY1Ni03MjgzNTBiZDgwZWMifQ.kMQGamEEPV-ZmjmelWPjqVOI1AIPaoQYTWrxWOAb_5I
@page = 1
@pageSize = 2
@name =
@email = com

GET {{baseUrl}}/customers?name={{name}}&email={{email}}&pageSize={{pageSize}}
Authorization: Bearer {{accessToken}}