@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQVVUSCIsImp0aSI6IjQ1ZDg5YTEyLTE4NzYtNDNhMS04Y2FlLTExYzE1NmRmMGI2ZSIsImlhdCI6MTc4OTgwNDMyMCwiZXhwIjoxNzg5ODA1MjIwLCJzdWIiOiIxNWMzMTU4MS0yOTk5LTQ0NDYtYTY1Ni03MjgzNTBiZDgwZWMifQ.Dn4kRFoAFiZM20SgzQW8C5C262Tovjnqkf2qfQwNB0M

GET {{baseUrl}}/customers
Authorization: Bearer {{accessToken}}