@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQVVUSCIsImp0aSI6ImZjMWQ5NDI1LTQyMGYtNDdjYi1iMzMwLTc3OTAwZTgwZWIzOCIsImlhdCI6MTc4OTgwMjM1MSwiZXhwIjoxNzg5ODAzMjUxLCJzdWIiOiIxNWMzMTU4MS0yOTk5LTQ0NDYtYTY1Ni03MjgzNTBiZDgwZWMifQ.ipeH4Nw1HIcP_PSYTOijp686SRkTHs6ssBI9w3vJNfA
@id = f7b0e576-5201-4e35-af68-17842449f0bb

PATCH {{baseUrl}}/customers/{{id}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Updated Customer Name",
  "phone": "9876543210",
  "email": "updated.customer@example.com",
  "externalReference": "EXT-1001",
  "status": "ACTIVE"
}