@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQVVUSCIsImp0aSI6IjkxMjUxNWE4LTIwODUtNDY3Ny1iNmUxLTQzMzBmZjc5NmQ4MCIsImlhdCI6MTc4OTgwMzI1NiwiZXhwIjoxNzg5ODA0MTU2LCJzdWIiOiIxNWMzMTU4MS0yOTk5LTQ0NDYtYTY1Ni03MjgzNTBiZDgwZWMifQ.mG79EmtnjmcLf5NLTV0H2FU1n1z5uLMLWtK28qHKgm8
@id = f7b0e576-5201-4e35-af68-17842449f0bb

PATCH {{baseUrl}}/customers/{{id}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Rio is me",
  "phone": "9876543210",
  "email": "rio.customer@example.com",
  "externalReference": "EXT-1001",
  "status": "ACTIVE"
}