@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQVVUSCIsImp0aSI6IjY2ODBiN2YxLWEzMTgtNDU1Mi05ZTYyLTk3ZGUzYjFiYWI4MCIsImlhdCI6MTc4OTk2NzUxOCwiZXhwIjoxNzg5OTY4NDE4LCJzdWIiOiJiZDA4Nzk2OS04YTBiLTQ0MDMtODhhNS02NGFlMmZmNjAwZmQifQ.dvLMZS18QEb2s4GLH65JgjDJm9RloLWKmxMWQ2Xs62s

GET {{baseUrl}}/organizations/current/members
Authorization: Bearer {{accessToken}}