POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "maya.rowan@northstar.example",
  "password": "Maya@123",
  "remember": true
}

> {%
    client.global.set("accessToken", response.body.accessToken);
%}