POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "elias.mercer@cedarline.example",
  "password": "Elias@123",
  "remember": true
}

> {%
    client.global.set("accessToken", response.body.accessToken);
%}